version: '3.4'

services:
  currencyquotation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  sql1:
    environment:
      SA_PASSWORD: "SenhaTeste123#*"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"