version: '3.4'

services:
  proxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20000:80"
  currencyquotation01:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20001:80"
  currencyquotation02:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20002:80"
  currencyquotation03:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20003:80"
  sql1:
    environment:
      SA_PASSWORD: "SenhaTeste123#*"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
  cache:
    ports:
      - "6379:6379"