version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:
  currencyquotation:
    image: currencyquotation
    build:
      context: .
      dockerfile: CurrencyQuotation/Dockerfile
    environment:
      DBServer: "dockersql.database"
    networks:
      - dockersql-network
    depends_on:
      - sql.database
    ports:
      - "62637:80"

  sql.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - dockersql-network